#!/usr/bin/python

import os, sys

_inputFile = None
_outputFile = None

def usage():
    print "There are two modes for convert_mkv_to_mp4:"
    print "1) Call: convert_mkv_to_mp4 -i FILE -o FILE"
    print "\tinput and output files are explicitly specified"
    print "2) Call: convert_mkv_to_mp4 FILE"
    print "\tthe supplied file is used for input"
    print "\ta new output file is created named after the input with an '.mp4' file extension."

def read_mode1():
    return sys.argv[2],sys.argv[4]

def read_mode2():
    if sys.argv[1].find(".") > 0:
        return sys.argv[1],sys.argv[1][:-len(os.path.splitext(sys.argv[1])[1])]+".mp4"
    else:
        return sys.argv[1],sys.argv[1]+".mp4"

def read():
    global input,output
    if len(sys.argv) == 2:
        _inputFile,_outputFile = read_mode2()
    elif len(sys.argv) == 5 and sys.argv[1] == '-i' and sys.argv[3] == '-o':
        _inputFile,_outputFile = read_mode1()
    else:
        print "Invalid call: convert_mkv_to_mp4",' '.join(sys.argv[1:])
        usage()
        sys.exit(2)
    if not os.path.exists(_inputFile):
        print "Invalid call: file '%s' does not exist!" % _inputFile
        sys.exit(2)
    if os.path.exists(_outputFile):
        _response = raw_input("Warning: file '%s' already exists! Should it be overwritten? [yes/no] " % _outputFile)
	if _response != "yes":
	    sys.exit(2)
    print "Converting %s into %s" % (_inputFile,_outputFile)

def main():
    read()

main()

#os.system("ls -l")
